Vagrant.configure("2") do |config|
  config.vm.hostname = "banco" -- Nome da vm
  config.vm.box = "centos/7" -- Nome/sistema operacional da caixa
  config.vm.network "private_network", ip: "192.168.1.4"  -- Tipo de rede / Endereço ip da vm
  config.vm.provision :shell, path: "../provisions/docker.sh" -- Roda um script de provisionamento assim que a vm é criada
  config.vm.network "forwarded_port", guest: 3306, host: 3306 -- Configurar porta do banco
  end