Vagrant.configure("2") do |config|
  config.vm.hostname = "front"
  config.vm.box = "centos/7" 
  config.vm.network "private_network", ip: "192.168.1.3" -- Tipo de rede / Endereço ip da vm
  config.vm.provision :shell, path: "../provisions/docker.sh" -- Roda um arquivo de provisionamento assim que a vm é criada
end