Vagrant.configure("2") do |config|
  config.vm.hostname = "controle" -- Nome da MÁQUINA VIRTUAL
  config.vm.box = "centos/7" -- Nome/SO da CAIXA
  config.vm.network "private_network", ip: "192.168.1.2" -- Tipo de rede / Endereço ip da vm
  config.vm.provision :shell, path: "../provisions/ansible.sh" -- Roda um script de provisionamento assim que a vm é criada
end